### ISSUE TITLE
Questions about generating data

### ISSUE THREAD

**Issue by zxpekko** [davidireland3/LeNSE#1]
graph = nx.read_gpickle(f"{graph_name}/main")
graph = relabel_graph(graph)
=======================================
Hello,when I generated data in the first step, there was a problem. I downloaded the text file of Wikitalk from the website you gave me, but these two sentences of code seemed to read a pickles file，these two codes come from 'get_train_test_graphs.py'. I didn't have this file, but only this text file. How can I get this pickles file?
Thanks.

**Comment by davidireland-iso** [comment]
Addressed in email -- will update readme file
