### ISSUE TITLE
fnames = glob.glob(f"{graph}/IC_{Type}_subgraphs/subgraph_*")

### ISSUE THREAD

**Issue by 19373254** [davidireland3/LeNSE#2]
hello, I think there is some problem with the readme file. There is not file in f"{graph}/IC_{Type}_subgraphs/subgraph_*". And I think the get_graph_sample_for_IC.py should be used, but this file is not mentioned in readme.

**Comment by davidireland-iso** [comment]
yes, you're right -- `get_graph_sample_for_IC.py` should be used. This allows us to pre-compute the subgraphs needed to evaluate the spread of a subset of nodes, along the lines of the original Kempe paper. If you send me an email we can discuss this further, or you can wait until I have time to update the readme.
